### ISSUE TITLE
Allow to configure Branches

### ISSUE THREAD

**Issue by 0x46616c6b** [mineiros-io/terraform-github-repository#107]
A last (for me) missing feature in this module is the possibility to configure branches (besides the default branch). For this [`github_branch`](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch) exists and could be easily integrated.

**Comment by soerenmartius** [comment]
Hi @0x46616c6b, 

Thanks for requesting this feature. I just opened a [PR](https://github.com/mineiros-io/terraform-github-repository/pull/111) for adding support for the `github_branch` resource.

**Comment by soerenmartius** [comment]
Hi @0x46616c6b,

We just released [v0.15.0](https://github.com/mineiros-io/terraform-github-repository/releases/tag/v0.15.0) which comes with support for the `github_branch` resource.

Thank You

**Comment by 0x46616c6b** [comment]
Thanks a lot!
