### ISSUE TITLE
Configure existing repositories

### ISSUE THREAD

**Issue by pypmannetjies** [mineiros-io/terraform-github-repository#109]
Is there a way to scan for repositories which already exist, and to apply the configuration to those? Or does this only apply to new projects?

**Comment by mariux** [comment]
hi @pypmannetjies,

You can import existing repositories using `terraform import` as usual. 

The module itself does not allow for just configuring existing repositories atm as the scope is to manage the full lifecycle of a repository including creation/deletion/archiving.

We recommend using [GitHub cli](https://github.com/cli/cli) to automate such tasks of importing bulk repositories. before you import the repositories need to be defined in code.

Does this answer your question?

**Comment by soerenmartius** [comment]
Will close this issue for now since it seems to be inactive. Please feel free to reopen it if needed. Thank you!
