### ISSUE TITLE
`delete_branch_on_merge` default in docs is incorrect

### ISSUE THREAD

**Issue by michael-careplanner** [mineiros-io/terraform-github-repository#114]
The docs state the default for `delete_branch_on_merge` is false, but [in the code](https://github.com/mineiros-io/terraform-github-repository/blob/main/main.tf#L19) it defaults to `true`.

Happy to submit a PR to fix by either changing the docs or the code, but not sure which is preferred. My personal opinion is that this should default to `false` as per the docs, so the code should be updated to reflect that, but this will change the behaviour for anyone who hasn't explicitly set this in their config so may need some more thought.

**Comment by soerenmartius** [comment]
Hi @michael-careplanner,

Thanks for reporting this. I will discuss this with the team and come back to you in a little time.

**Comment by mariux** [comment]
@michael-careplanner nice catch... yes the docs would need to be adjusted here. the chosen default is based on what we saw in most use cases and that's why it differs from the provider here.

**Comment by soerenmartius** [comment]
I just added a PR in #115 for adjusting the docs. Again @michael-careplanner , thanks for reporting this!
