### ISSUE TITLE
Allow compatibility for pages and environments

### ISSUE THREAD

**Issue by rgupta-mwb** [mineiros-io/terraform-github-repository#118]
Hi, I have been trying to import some repos into a master repo forked from this, but some repositories couldn't be imported because the module doesn't support pages or environments which a repo may have. Is there anything we can do about this, even if it is just so it doesn't make any change to it but allows me to import the repo?

**Comment by mariux** [comment]
hi @rgupta-mwb..

thank you for taking the time to report this.

> the module doesn't support pages or environments which a repo may have.

pages are supported and documented here: https://github.com/mineiros-io/terraform-github-repository#var-pages

I am not quiet sure what you mean by environments: We did not yet implemented the [github_repository_environment](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_environment) resource. 

But this should not block you from importing as it is an independent resource that can also be used outside of the module until the module adds support for this.

How does your code look like? What command do you use to import and what errors do you get?

**Comment by soerenmartius** [comment]
Hi @rgupta-mwb , just following up on this. Would it be possible to get your input? Otherwise we would close this request soon.

Thanks and have a good evening
Soren
