### ISSUE TITLE
Feature Request: github_app_installation_repository

### ISSUE THREAD

**Issue by anthr76** [mineiros-io/terraform-github-repository#119]
https://registry.terraform.io/providers/integrations/github/latest/docs/resources/app_installation_repository

It would be useful to have support for this within the module.

**Comment by anthr76** [comment]
It looks like you beat me to the punch. Thanks!

**Comment by soerenmartius** [comment]
Hey @anthr76 , we just released [v0.16.1](https://github.com/mineiros-io/terraform-github-repository/releases/tag/v0.16.1) now :) Let me know if there's anything else we can do for you
