### ISSUE TITLE
Add Support for Branch Protections (v4)

### ISSUE THREAD

**Issue by jrmash** [mineiros-io/terraform-github-repository#124]
A couple of months ago, GitHub released a configuration option for branch protections that allows specified users to [bypass pull request restrictions](https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/). Support for this feature recently made it's way to the GitHub Terraform provider:

- https://github.com/integrations/terraform-provider-github/pull/1030

There does not appear to be an equivalent in the `branch_protection_v3` resource ([yet?](https://github.com/integrations/terraform-provider-github/issues/1005)), so this is a request to add support for `branch_protection`.

**Comment by soerenmartius** [comment]
Hi @jrmash ,

Thanks for requesting it. We are planning to implement this in the future but it may take some time as we are currently working on higher priorities that we need to resolve first. I will keep you posted and come back to you in this issue once we provided an update. In the meantime, we welcome you to contribute to this repository also!

Thanks,
Soren
