### ISSUE TITLE
Partial failure if the repository name contains any space

### ISSUE THREAD

**Issue by btlogy** [mineiros-io/terraform-github-repository#161]
The module seems to allow spaces to be used in the [name](https://github.com/mineiros-io/terraform-github-repository/blob/ee6001a0b791af814d7f0c015da0c7ca204f3fbe/variables.tf#L6-L9) of the repository.

It will apparently converts them into `-` while building the plan (I've not found yet where this is done).

However, it partially fails to apply the plan: the repository will be created in GitHub but Terraform will fail.

#### How to reproduce

1. Create a new repository like this:
```
module "space_repo" {
  source  = "mineiros-io/repository/github"
  version = "~> 0.18.0"

  name = "space repo"
}
```

2.  Execute `terraform plan` - should give something like this:
   ```
  # module.space_repo.github_repository.repository will be created
  + resource "github_repository" "repository" {
      ...
      + name = "space repo"
      ...
    }
   ```

3. Execute `terraform apply` - should fail with this error:
```
module.space_repo.github_repository.repository: Creating...

Error: PATCH https://api.github.com/repos/my-org/space-repo: 422 Validation Failed []

  with module.space_repo.github_repository.repository,
  on .terraform/modules/space_repo/main.tf line 91, in resource "github_repository" "repository":
  91: resource "github_repository" "repository" {
```

4. Subsequent `terrafrom apply` should fail again with this other error:
```
module.space_repo.github_repository.repository: Destroying... [id=space-repo]
module.space_repo.github_repository.repository: Destruction complete after 0s
module.space_repo.github_repository.repository: Creating...

Error: POST https://api.github.com/orgs/my-org/repos: 422 Repository creation failed. [{Resource:Repository Field:name Code:custom Message:name already exists on this account}]

  with module.space_repo.github_repository.repository,
  on .terraform/modules/space_repo/main.tf line 91, in resource "github_repository" "repository":
  91: resource "github_repository" "repository" {
```
(Because [`archive_on_destroy`](https://github.com/mineiros-io/terraform-github-repository#var-archive_on_destroy) is set to `true` by default I suppose).

#### Expected behavior

I suppose the `terraform plan` command should explicitly fail and report the presence of invalid character(s) in the name.

**Comment by mariux** [comment]
Hi @btlogy 

thanks for bringing this to our attention. The errors you see are from the provider not from the module. GitHub does not allow spaces in names and converts them to dashes. The provider does not seem to care about validation here.

As we are just shifting this responsibility to the provider and they are shifting it to the API the error you see is expected.

The upstream error can be tracked here: https://github.com/integrations/terraform-provider-github/issues/1215 maybe you wanna upvote it there ;)

The solution here is to not try to create repositories with spaces but use dashes right away as even GitHub UI adds the dashes for you: 
![Screenshot 2023-07-21 at 18-29-05 New repository](https://github.com/mineiros-io/terraform-github-repository/assets/918717/491f7130-3a99-4ac4-be83-ef8c5b6cd92b)

**Comment by btlogy** [comment]
Hi @mariux

Thank you this quick answer.
I did not trace the root cause back to the provider: thank you for pointing to this issue.

Before reading your comment, I was considering to propose a PR using [input-variable-validation](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions#input-variable-validation) here to avoid space in the name:

https://github.com/mineiros-io/terraform-github-repository/blob/ee6001a0b791af814d7f0c015da0c7ca204f3fbe/variables.tf#L6-L9

Should I try to do this upstream instead?

**Comment by btlogy** [comment]
> The solution here is to not try to create repositories with spaces...

In our case, we do not have control on the input, so we have rely on the input being validated by either the module and/or the provider.

**Comment by btlogy** [comment]
Something like this would do for us now:

* #162

While waiting for you feedback (@mariux), I'll investigate if this could/should be done in the provider instead...

**Comment by btlogy** [comment]
It will likely be harder for me to fix the provider, but I can try:

* integrations/terraform-provider-github/pull/1806

**Comment by btlogy** [comment]
Hi @mariux

I've submitted my PR above for the provider.
Maybe you can have a look and upvote it if sensible.

**Comment by btlogy** [comment]
Cool, the pull request has been merged in the provider repository: the [latest](https://registry.terraform.io/providers/integrations/github/latest) version (`v5.32.0`) should enforce character validation.
@mariux: how do we get this feature in this module (`terraform init -upgrade` still gives me `integrations/github v4.31.0`)?

**Comment by btlogy** [comment]
> Cool, the pull request has been merged in the provider repository: the [latest](https://registry.terraform.io/providers/integrations/github/latest) version (`v5.32.0`) should enforce character validation. @mariux: how do we get this feature in this module (`terraform init -upgrade` still gives me `integrations/github v4.31.0`)?

Nevermind: I've not seen we are still using `v0.8.0` of module `github_team` which might prevent us to upgrade...

**Comment by btlogy** [comment]
I can confirm here that provider `v5.32.0` fixes this issue
