### ISSUE TITLE
thoughts about defaults for 0.1.0

### ISSUE THREAD

**Issue by mariux** [mineiros-io/terraform-github-repository#5]
i would like to discuss changing some defaults in this early phase:

- change `private` to default to `true` to make it more secure/private by default.

- change `has_issues` to default to `false` so you have to specify the features you want to have and not those you do not want to have (opt-in instead of out) In addition this would be more consistent with other `has_*` options (and match the current description)

- set `allow_merge_commit`, `allow_squash_merge` and `allow_rebase_merge` to `false` so that you have to opt-in and are forced to specify at least one.

**Comment by soerenmartius** [comment]
Yes I agree, let's implement this for the next release.
