### ISSUE TITLE
Fix warning from GitHub Provider

### ISSUE THREAD

**Issue by anavarreteuk** [mineiros-io/terraform-github-repository#57]
Hi, it seems private has been deprecated for visibility.

I have got the below warning when terraforming --->

`Warning: "private": [DEPRECATED] use visibility instead`

**Comment by mariux** [comment]
HI @anavarreteuk,

thank you for your report. Yes, we are aware of this but thought about keeping backward compatibility to the Github provider 2.x  as long as possible.
We already have support for Github provider 4.x on our roadmap and will most likely drop 2.x support in the same upcoming release and getting rid of this annoying warning in a future version.

We will keep you updated here and start working on 4.x support asap.

**Comment by ibrahimcanyilmaz** [comment]
Hi @mariux! is there any updates about this issue ?

**Comment by mariux** [comment]
hi @ibrahimcanyilmaz, @anavarreteuk

we looke dinto it in our last planning meeting and noticed this change was introduced in 2.x branch shortly before 3.x release.
So this does not seem to break compatibility with 2.x provider if we implement it and we removed the dependency to upgrading to 4.x from our internal planning.

We can not yet tell when we will have time to deprecate private in the module. If someone provides a patch we will be happy to review and merge it.

for reference: steps to implement afaics (pls double check):
- let `private` default to `null`
- add `visibility` argument defaulting to `private` if `var.private` is not set or `public` if `var.private = false`.
- add `visibility` support to `defaults` 
- update docs
- increase minimum provider version to `2.9.0`
