### ISSUE TITLE
Documentation about dismiss_stale_reviews does not match with the result

### ISSUE THREAD

**Issue by mrodm** [mineiros-io/terraform-github-repository#83]
Hi,
Checking about protected branches and the key `required_pull_request_reviews`, documentation about the `dismiss_stale_reviews` setting mentions that the default value is `false`.
However, when running a plan adding a protected branch without setting that value, as this:

```
 branch_protections = [
  {
    branch         = "master"
    enforce_admins = false
    required_pull_request_reviews = {
      require_code_owner_reviews      = true
      required_approving_review_count = 2
    },
    restrictions = {
      apps  = []
      teams = ["novum-moves"]
      users = []
    }
  },
]
```

a terraform plan is going to set this setting as `true`.
```
  # module.repository.github_branch_protection_v3.branch_protection[0] will be created
  + resource "github_branch_protection_v3" "branch_protection" {
      + branch                 = "master"
      + enforce_admins         = false
      + etag                   = (known after apply)
      + id                     = (known after apply)
      + repository             = "repository"
      + require_signed_commits = false

      + required_pull_request_reviews {
          + dismiss_stale_reviews           = true
          + require_code_owner_reviews      = true
          + required_approving_review_count = 2
        }

      + restrictions {
          + teams = [
              + "novum-moves",
            ]
        }
    }
```

Checking `main.tf`, I think this value comes from this merge:
https://github.com/mineiros-io/terraform-github-repository/blob/master/main.tf#L67

Tested version:
```
module "repository" {
  source                                = "mineiros-io/repository/github"
  version                               = "0.10.1"
  ...
}
```

Not sure what it should be updated, documentation or code ? 
I could open a PR to update the needed value.

Thanks!

**Comment by soerenmartius** [comment]
Hi @mrodm ,

Thanks for reporting this issue. Let me clarify this with the team. My guess is that we want to have the default value of `dismiss_stale_reviews` set to `true` which would mean that we have an error in the documentation. I will come back to you later today. Again, thanks for reporting this issue.

**Comment by soerenmartius** [comment]
Hi @mrodm,

We fixed the documentation in https://github.com/mineiros-io/terraform-github-repository/pull/84

Again, thanks for reporting this issue!
