### ISSUE TITLE
Wrong visibility in example?

### ISSUE THREAD

**Issue by pickgr** [mineiros-io/terraform-github-repository#87]
The example for a public repos sets:

`visibility         = "private"`

Is this an oversight?

**Comment by soerenmartius** [comment]
Hey! Thanks for reporting this! You're absolutely right - this should be set to `public` instead. Will provide a fix in a min. Thank You!

**Comment by soerenmartius** [comment]
Fixed in https://github.com/mineiros-io/terraform-github-repository/pull/88
