### ISSUE TITLE
Example not runnable?

### ISSUE THREAD

**Issue by kondensatorn** [mineiros-io/terraform-github-repository#90]
I don't know if the example is supposed to be runnable without modification, but the result when I try to do that is (after a successful "terraform init"):
➜ terraform plan
╷
│ Error: Invalid count argument
│
│   on .terraform/modules/repository/main.tf line 162, in resource "github_branch_protection_v3" "branch_protection":
│  162:   count = length(local.branch_protections)
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around
│ this, use the -target argument to first apply only the resources that the count depends on.
╵

**Comment by soerenmartius** [comment]
Hi @kondensatorn , thanks for reporting this! It seems like the example is outdated! I will provide a new and updated example in a minute! Thank you

**Comment by soerenmartius** [comment]
Hi @kondensatorn , I just updated the example to a working version now. That should be helpful! Again, thanks for bringing this to our attention :)

**Comment by kondensatorn** [comment]
Thanks @soerenmartius!
