### ISSUE TITLE
 Add parameter allow_auto_merge

### ISSUE THREAD

**Issue by jworks-mwb** [mineiros-io/terraform-github-repository#93]
From provider [docs](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository):
allow_auto_merge - (Optional) Set to true to allow auto-merging pull requests on the repository.

**Comment by soerenmartius** [comment]
Hi @jworks-mwb,

Thanks for bringing this to our attention. I will provide a PR during the weekend to add this relatively new feature! Thank You!

**Comment by jworks-mwb** [comment]
@soerenmartius I have a branch here https://github.com/jworks-mwb/terraform-github-repository/tree/feature/allow_auto_merge but I haven't been able to find the time to update the unit tests.

**Comment by jworks-mwb** [comment]
@soerenmartius It looks like you've added `allow_auto_merge` to the variables, but it wasn't added to the main.tf/github_repository.repository resource here https://github.com/mineiros-io/terraform-github-repository/blob/main/main.tf#L91. So setting this variable has no affect.

**Comment by soerenmartius** [comment]
@jworks-mwb that's correct - thanks for spotting this. Seems like I've forgotten to add it to the resource while being in a hurry. Sorry for that. I've provided a fix in #97 and will issue a new release tomorrow

**Comment by jworks-mwb** [comment]
No problem, and thank you for the addition of this new argument, and your quick responses.
